packages:
  - apps/desktop
  - packages/*

overrides:
  esbuild: 0.28.1
  "undici@>=6.25.0 <6.28.1": 6.28.1
  "undici@>=7.28.0 <7.29.1": 7.29.1

onlyBuiltDependencies:
  - electron
  - esbuild

allowBuilds:
  electron-winstaller: set this to true or false
  esbuild: set this to true or false
