packages:
  - apps/desktop
  - packages/*

overrides:
  esbuild: 0.28.1

onlyBuiltDependencies:
  - electron
  - esbuild

allowBuilds:
  electron-winstaller: set this to true or false
  esbuild: set this to true or false
