import { useMemo, useState } from "react";
import type { DirectoryEmployee, WorkspaceDepartment } from "@yuksalish/contracts";
import { Avatar, Button, Checkbox, Field, Input } from "@fluentui/react-components";
import { Add20Regular, Building20Regular, PeopleTeam20Regular, Search20Regular } from "@fluentui/react-icons";
import { WorkspaceSelect as Select } from "./WorkspaceSelect";
import { createDepartment, updateDepartment, updateDepartmentMembers } from "./workspace-api";
import { EmployeeProfileLink } from "./EmployeeProfileLink";
import { EmployeeScopeSwitch } from "./EmployeeScopeSwitch";
import { employeeScope, type EmployeeScope } from "./employee-scope";

interface Props { readonly token: string; readonly departments: readonly WorkspaceDepartment[]; readonly employees: readonly DirectoryEmployee[]; readonly onChanged: (value: WorkspaceDepartment) => void }

export function normalizeDepartmentCode(value: string): string {
  return value.toLocaleLowerCase("en-US")
    .replace(/\s+/gu, "-")
    .replace(/[^a-z0-9_-]/gu, "")
    .replace(/^[^a-z0-9]+/u, "")
    .slice(0, 64);
}

function orderedDepartments(departments: readonly WorkspaceDepartment[]) {
  const children = new Map<string, WorkspaceDepartment[]>();
  for (const item of departments) { const key = item.parentId ?? "root"; children.set(key, [...(children.get(key) ?? []), item]); }
  for (const values of children.values()) values.sort((a, b) => a.name.localeCompare(b.name, "ru"));
  const result: { department: WorkspaceDepartment; depth: number }[] = []; const visited = new Set<string>();
  const visit = (parentId: string, depth: number) => { for (const item of children.get(parentId) ?? []) { if (visited.has(item.id)) continue; visited.add(item.id); result.push({ department: item, depth }); visit(item.id, depth + 1); } };
  visit("root", 0); for (const item of departments) if (!visited.has(item.id)) result.push({ department: item, depth: 0 }); return result;
}

export function DepartmentManagement({ token, departments, employees, onChanged }: Props) {
  const ordered = useMemo(() => orderedDepartments(departments), [departments]);
  const [selectedId, setSelectedId] = useState(() => departments.find((item) => employeeScope(item.id, departments) === "central")?.id ?? "");
  const selected = departments.find((item) => item.id === selectedId);
  const [newName, setNewName] = useState(""); const [newCode, setNewCode] = useState(""); const [newParentId, setNewParentId] = useState("");
  const [newScope, setNewScope] = useState<EmployeeScope>("central");
  const [directoryScope, setDirectoryScope] = useState<EmployeeScope>("central");
  const [showCreate, setShowCreate] = useState(false);
  const [name, setName] = useState(selected?.name ?? ""); const [code, setCode] = useState(selected?.code ?? ""); const [parentId, setParentId] = useState(selected?.parentId ?? "");
  const [scope, setScope] = useState<EmployeeScope>(employeeScope(selected?.id, departments));
  const [memberIds, setMemberIds] = useState<ReadonlySet<string>>(new Set(selected?.memberIds ?? [])); const [memberQuery, setMemberQuery] = useState("");
  const [memberScope, setMemberScope] = useState<EmployeeScope>(employeeScope(selected?.id, departments));
  const [leadUserId, setLeadUserId] = useState(selected?.leadUserId ?? "");
  const [busy, setBusy] = useState(false); const [feedback, setFeedback] = useState("");
  const [feedbackIsError, setFeedbackIsError] = useState(false);
  const invalidParentIds = useMemo(() => { const result = new Set<string>(selectedId ? [selectedId] : []); let changed = true; while (changed) { changed = false; for (const item of departments) if (item.parentId && result.has(item.parentId) && !result.has(item.id)) { result.add(item.id); changed = true; } } return result; }, [departments, selectedId]);
  const visibleEmployees = employees.filter((employee) => employee.status === "active" && employeeScope(employee.departmentId, departments) === memberScope && (!memberQuery.trim() || `${employee.name} ${employee.jobTitle ?? ""}`.toLocaleLowerCase("ru").includes(memberQuery.trim().toLocaleLowerCase("ru"))));
  const visibleDepartments = ordered.filter(({ department }) => employeeScope(department.id, departments) === directoryScope);
  const selectDepartment = (item: WorkspaceDepartment) => { const effectiveScope = employeeScope(item.id, [...departments, item]); setSelectedId(item.id); setName(item.name); setCode(item.code); setParentId(item.parentId ?? ""); setScope(effectiveScope); setMemberScope(effectiveScope); setMemberIds(new Set(item.memberIds ?? [])); setLeadUserId(item.leadUserId ?? ""); setMemberQuery(""); setFeedback(""); };
  const changeDirectoryScope = (next: EmployeeScope) => { setDirectoryScope(next); const first = ordered.find(({ department }) => employeeScope(department.id, departments) === next); if (first) selectDepartment(first.department); else setSelectedId(""); };
  const add = async () => { const normalizedCode = normalizeDepartmentCode(newCode); if (!newName.trim() || !normalizedCode || busy) return; setBusy(true); setFeedback(""); setFeedbackIsError(false); try { const created = await createDepartment(token, { name: newName.trim(), code: normalizedCode, scope: newScope, parentId: newParentId || undefined }); onChanged(created); selectDepartment(created); setDirectoryScope(newScope); setNewName(""); setNewCode(""); setNewParentId(""); setShowCreate(false); setFeedback("Подразделение создано. Служебная группа готова."); } catch (error) { setFeedbackIsError(true); setFeedback(error instanceof Error ? error.message : "Не удалось создать подразделение"); } finally { setBusy(false); } };
  const save = async () => { const normalizedCode = normalizeDepartmentCode(code); if (!selected || !name.trim() || !normalizedCode || busy) return; setBusy(true); setFeedback(""); setFeedbackIsError(false); try { const saved = await updateDepartment(token, selected.id, { name: name.trim(), code: normalizedCode, parentId: parentId || null, scope }); onChanged(saved); setCode(normalizedCode); setDirectoryScope(scope); setMemberScope(scope); setFeedback("Сведения о подразделении сохранены."); } catch (error) { setFeedbackIsError(true); setFeedback(error instanceof Error ? error.message : "Не удалось сохранить подразделение"); } finally { setBusy(false); } };
  const saveMembers = async () => { if (!selected || busy) return; setBusy(true); setFeedback(""); setFeedbackIsError(false); try { const saved = await updateDepartmentMembers(token, selected.id, [...memberIds]); onChanged(saved); setLeadUserId(saved.leadUserId ?? ""); setFeedback("Состав отдела и служебной группы обновлён."); } catch (error) { setFeedbackIsError(true); setFeedback(error instanceof Error ? error.message : "Не удалось обновить состав отдела"); } finally { setBusy(false); } };
  const saveLead = async () => { if (!selected || busy) return; setBusy(true); setFeedback(""); setFeedbackIsError(false); try { const saved = await updateDepartment(token, selected.id, { leadUserId: leadUserId || null }); onChanged(saved); setLeadUserId(saved.leadUserId ?? ""); setFeedback(saved.leadUserId ? "Главное лицо назначено. Оно сможет отправлять отчёт от имени подразделения." : "Назначение главного лица снято."); } catch (error) { setFeedbackIsError(true); setFeedback(error instanceof Error ? error.message : "Не удалось назначить главное лицо"); } finally { setBusy(false); } };
  return <section className="department-management" aria-label="Отделы и подразделения" aria-busy={busy}>
    <header className="directory-subheading department-hero"><span className="department-hero-icon"><Building20Regular /></span><div><h2>Отделы и подразделения</h2><p>Структура команды, принадлежность к ЦА или регионам и состав служебных групп.</p></div><Button appearance="primary" icon={<Add20Regular />} disabled={busy} aria-expanded={showCreate} onClick={() => setShowCreate((value) => !value)}>Новое подразделение</Button></header>
    {feedback ? <div className="directory-feedback" role={feedbackIsError ? "alert" : "status"}>{feedback}</div> : null}
    {showCreate ? <div className="department-create-card"><div className="department-card-heading"><h3>Новое подразделение</h3><p>Тип определяет, в каком списке будут видны сотрудники.</p></div><EmployeeScopeSwitch value={newScope} disabled={busy} onChange={(next) => { setNewScope(next); setNewParentId(""); }} label="Тип нового подразделения" /><div className="department-create-grid"><Field label="Название"><Input aria-label="Название нового отдела" value={newName} disabled={busy} onChange={(_, data) => setNewName(data.value)} /></Field><Field label="Короткий код" hint="Латиницей, без пробелов"><Input aria-label="Код нового отдела" value={newCode} disabled={busy} onChange={(_, data) => setNewCode(normalizeDepartmentCode(data.value))} /></Field><Field label="Расположение"><Select aria-label="Расположение нового отдела" value={newParentId} disabled={busy} onChange={(event) => setNewParentId(event.target.value)}><option value="">Самостоятельное подразделение</option>{ordered.filter(({ department }) => employeeScope(department.id, departments) === newScope).map(({ department, depth }) => <option key={department.id} value={department.id}>{"— ".repeat(depth)}{department.name}</option>)}</Select></Field><Button appearance="primary" disabled={busy || !newName.trim() || !newCode.trim()} onClick={() => void add()}>Создать</Button></div></div> : null}
    <div className="department-workspace"><aside className="department-tree" aria-label="Список подразделений"><div className="department-tree-top"><strong>Структура</strong><small>{visibleDepartments.length} подразделений</small></div><EmployeeScopeSwitch value={directoryScope} disabled={busy} onChange={changeDirectoryScope} label="Тип подразделений" /><div className="department-tree-list">{visibleDepartments.map(({ department, depth }) => <button key={department.id} type="button" aria-current={department.id === selectedId ? "true" : undefined} className={department.id === selectedId ? "selected" : ""} style={{ paddingInlineStart: `${14 + depth * 16}px` }} disabled={busy} onClick={() => selectDepartment(department)}><strong>{department.name}</strong><small>{department.assignedUsersCount} сотрудников</small></button>)}{!visibleDepartments.length ? <p className="department-empty">Здесь пока нет подразделений.</p> : null}</div></aside>
      {selected && employeeScope(selected.id, departments) === directoryScope ? <div className="department-editor"><div className="department-card-heading"><span className="department-card-icon"><Building20Regular /></span><div><h3>{selected.name}</h3><p>{scope === "regional" ? "Региональное подразделение" : "Центральный аппарат"} · {selected.assignedUsersCount} сотрудников</p></div></div><div className="department-editor-fields"><Field label="Название"><Input aria-label="Название отдела" value={name} disabled={busy} onChange={(_, data) => setName(data.value)} /></Field><Field label="Короткий код" hint="Латиницей, без пробелов"><Input aria-label="Код отдела" value={code} disabled={busy} onChange={(_, data) => setCode(normalizeDepartmentCode(data.value))} /></Field></div><div className="department-editor-fields"><Field label="Расположение"><Select aria-label="Расположение отдела" value={parentId} disabled={busy} onChange={(event) => setParentId(event.target.value)}><option value="">Самостоятельное подразделение</option>{ordered.filter(({ department }) => !invalidParentIds.has(department.id) && employeeScope(department.id, departments) === scope).map(({ department, depth }) => <option key={department.id} value={department.id}>{"— ".repeat(depth)}{department.name}</option>)}</Select></Field><div className="department-scope-field"><span>Тип подразделения</span><EmployeeScopeSwitch value={scope} disabled={busy} onChange={(next) => { setScope(next); setParentId(""); }} label="Тип выбранного подразделения" /></div></div><div className="department-editor-actions"><Button disabled={busy || !name.trim() || !code.trim()} onClick={() => void save()}>Сохранить сведения</Button></div>
        <section className="department-members-section"><div className="department-members-heading"><div><PeopleTeam20Regular /><span><strong>Сотрудники подразделения</strong><small>{memberIds.size} выбрано</small></span></div><p>Служебная группа автоматически получает тот же состав.</p></div><EmployeeScopeSwitch value={memberScope} disabled={busy} onChange={setMemberScope} label="Сотрудники для добавления" /><Input contentBefore={<Search20Regular />} aria-label="Поиск сотрудников для отдела" placeholder="Найти сотрудника" value={memberQuery} onChange={(_, data) => setMemberQuery(data.value)} /><div className="department-member-list" role="group" aria-label={`Сотрудники отдела ${selected.name}`}>{visibleEmployees.map((employee) => <div key={employee.id} className="department-member-row"><Checkbox aria-label={`Добавить ${employee.name}`} checked={memberIds.has(employee.id)} disabled={busy} onChange={(_, data) => setMemberIds((current) => { const next = new Set(current); if (data.checked === true) next.add(employee.id); else next.delete(employee.id); return next; })} /><EmployeeProfileLink userId={employee.id} personName={employee.name}><Avatar name={employee.name} size={32} color="colorful" /><span><strong>{employee.name}</strong><small>{employee.jobTitle ?? "Должность не указана"}</small></span></EmployeeProfileLink></div>)}{!visibleEmployees.length ? <p className="department-empty">Сотрудники не найдены.</p> : null}</div><Button appearance="primary" disabled={busy} onClick={() => void saveMembers()}>Сохранить состав</Button></section>
        <section className="department-members-section"><Field label="Главное лицо отдела или подразделения" hint="Сначала сохраните состав. Только выбранный сотрудник сможет отправлять отчёт от имени команды."><Select aria-label="Главное лицо отдела или подразделения" value={leadUserId} disabled={busy} onChange={(event) => setLeadUserId(event.target.value)}><option value="">Не назначено</option>{employees.filter((employee) => employee.status === "active" && selected.memberIds?.includes(employee.id)).map((employee) => <option key={employee.id} value={employee.id}>{employee.name}</option>)}</Select></Field><Button disabled={busy || (selected.leadUserId ?? "") === leadUserId} onClick={() => void saveLead()}>Сохранить главное лицо</Button></section>
      </div> : <div className="directory-empty">Выберите подразделение слева или создайте новое.</div>}</div>
  </section>;
}
