import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Button, Input, Textarea, Tooltip } from "@fluentui/react-components";
import { Add24Regular, ArrowDownload24Regular, ArrowRedo24Regular, ArrowUndo24Regular, BranchFork24Regular, CheckmarkCircle24Regular, CircleEdit24Regular, Delete24Regular, Dismiss24Regular, Save24Regular } from "@fluentui/react-icons";
import { addEdge, Background, BackgroundVariant, Controls, Handle, MarkerType, MiniMap, Position, ReactFlow, useEdgesState, useNodesState, type Connection, type Edge, type Node, type NodeProps, type NodeTypes } from "@xyflow/react";
import "@xyflow/react/dist/style.css";
import type { ApprovalNodeData, ApprovalNodeKind, WorkflowDefinition, WorkflowPosition, WorkspacePerson } from "@yuksalish/contracts";
import { WorkspaceSelect } from "./WorkspaceSelect";

type FlowNode = Node<ApprovalNodeData>;
interface FlowEdgeData extends Record<string, unknown> { readonly outcome: string; readonly condition: Readonly<Record<string, unknown>>; readonly sortOrder: number; }
type FlowEdge = Edge<FlowEdgeData>;
interface Props {
  readonly workflow: WorkflowDefinition; readonly processName: string; readonly accent: "project" | "trip";
  readonly people?: readonly WorkspacePerson[]; readonly positions?: readonly WorkflowPosition[];
  readonly onSave: (workflow: WorkflowDefinition) => Promise<void> | void;
  readonly onPublish: (workflow: WorkflowDefinition) => Promise<WorkflowDefinition | undefined> | WorkflowDefinition | undefined;
}
const labels: Readonly<Record<ApprovalNodeKind, string>> = { start: "Старт", approval: "Согласование", condition: "Условие", parallel: "Параллельные ветки", correction: "Доработка", end: "Завершение" };
function FlowObject({ data, selected }: NodeProps<FlowNode>) { return <div className={`workflow-object-node${selected ? " is-selected" : ""}`}><Handle type="target" position={Position.Left} /><div className="workflow-object-heading"><i /><span>{labels[data.kind]}</span></div><strong>{data.label}</strong>{data.detail ? <small>{data.detail}</small> : null}<Handle type="source" position={Position.Right} /></div>; }
const nodeTypes: NodeTypes = { approvalObject: FlowObject };
const toNodes = (workflow: WorkflowDefinition): FlowNode[] => workflow.nodes.map((node) => ({ id: node.id, type: "approvalObject", position: { x: node.positionX, y: node.positionY }, data: { ...node.config, label: node.label, kind: node.kind, detail: node.detail }, className: `workflow-node node-${node.kind}` }));
const toEdges = (workflow: WorkflowDefinition): FlowEdge[] => workflow.edges.map((edge) => ({ id: edge.id, source: edge.source, target: edge.target, label: edge.label, data: { outcome: edge.outcome, condition: edge.condition, sortOrder: edge.sortOrder }, markerEnd: { type: MarkerType.ArrowClosed } }));
const keyOf = (nodes: readonly FlowNode[], edges: readonly FlowEdge[]) => JSON.stringify({ nodes: nodes.map(({ id, position, data }) => ({ id, position, data })), edges: edges.map(({ id, source, target, label, data }) => ({ id, source, target, label, data })) });
interface Snapshot { readonly nodes: readonly FlowNode[]; readonly edges: readonly FlowEdge[]; readonly selectedId: string; }
const clone = (nodes: readonly FlowNode[], edges: readonly FlowEdge[], selectedId: string): Snapshot => ({ nodes: nodes.map((node) => ({ ...node, position: { ...node.position }, data: { ...node.data } })), edges: edges.map((edge) => ({ ...edge, data: edge.data ? { ...edge.data, condition: { ...edge.data.condition } } : undefined })), selectedId });

export function ProcessWorkflowDesigner({ workflow, processName, accent, people = [], positions = [], onSave, onPublish }: Props) {
  const preparedNodes = useMemo(() => toNodes(workflow), [workflow]); const preparedEdges = useMemo(() => toEdges(workflow), [workflow]);
  const [nodes, setNodes, onNodesChange] = useNodesState<FlowNode>(preparedNodes); const [edges, setEdges, onEdgesChange] = useEdgesState<FlowEdge>(preparedEdges);
  const [selectedId, setSelectedId] = useState(preparedNodes[0]?.id ?? ""); const [baseline, setBaseline] = useState(() => keyOf(preparedNodes, preparedEdges));
  const [undoStack, setUndoStack] = useState<readonly Snapshot[]>([]); const [redoStack, setRedoStack] = useState<readonly Snapshot[]>([]); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const dragStart = useRef<Snapshot | undefined>(undefined);
  const selected = nodes.find((node) => node.id === selectedId); const changed = keyOf(nodes, edges) !== baseline;
  const snapshot = useCallback(() => clone(nodes, edges, selectedId), [edges, nodes, selectedId]);
  const restore = useCallback((value: Snapshot) => { setNodes([...value.nodes]); setEdges([...value.edges]); setSelectedId(value.selectedId); }, [setEdges, setNodes]);
  const checkpoint = useCallback(() => { setUndoStack((current) => [...current.slice(-99), snapshot()]); setRedoStack([]); setMessage(""); }, [snapshot]);
  const undo = useCallback(() => { const previous = undoStack.at(-1); if (!previous) return; setRedoStack((current) => [...current, snapshot()]); setUndoStack((current) => current.slice(0, -1)); restore(previous); }, [restore, snapshot, undoStack]);
  const redo = useCallback(() => { const next = redoStack.at(-1); if (!next) return; setUndoStack((current) => [...current, snapshot()]); setRedoStack((current) => current.slice(0, -1)); restore(next); }, [redoStack, restore, snapshot]);
  useEffect(() => { const handler = (event: KeyboardEvent) => { if (!event.ctrlKey || event.altKey || event.metaKey || event.isComposing || event.key.toLowerCase() !== "z") return; event.preventDefault(); if (event.shiftKey) redo(); else undo(); }; window.addEventListener("keydown", handler, true); return () => window.removeEventListener("keydown", handler, true); }, [redo, undo]);
  const update = (patch: Partial<ApprovalNodeData>) => { checkpoint(); setNodes((current) => current.map((node) => node.id === selectedId ? { ...node, data: { ...node.data, ...patch } } : node)); };
  const add = (kind: ApprovalNodeKind) => { checkpoint(); const id = `${kind}-${crypto.randomUUID()}`; setNodes((current) => [...current, { id, type: "approvalObject", position: { x: 360 + current.length * 18, y: 190 + current.length * 12 }, data: { label: labels[kind], kind, detail: "Настройте правило" }, className: `workflow-node node-${kind}` }]); setSelectedId(id); };
  const connect = (connection: Connection) => { checkpoint(); const source = nodes.find((node) => node.id === connection.source); setEdges((current) => addEdge({ ...connection, data: { outcome: source?.data.kind === "parallel" ? "branch" : "approve", condition: {}, sortOrder: current.filter((edge) => edge.source === connection.source).length }, markerEnd: { type: MarkerType.ArrowClosed } }, current)); };
  const definition = (): WorkflowDefinition => ({ ...workflow, nodes: nodes.map((node) => ({ id: node.id, kind: node.data.kind, label: node.data.label, detail: node.data.detail, positionX: node.position.x, positionY: node.position.y, config: Object.fromEntries(Object.entries(node.data).filter(([key]) => !["label", "kind", "detail"].includes(key))) })), edges: edges.map((edge, index) => ({ id: edge.id, source: edge.source, target: edge.target, outcome: edge.data?.outcome ?? "approve", label: typeof edge.label === "string" ? edge.label : null, condition: edge.data?.condition ?? {}, sortOrder: edge.data?.sortOrder ?? index })) });
  const save = async () => { setBusy(true); setMessage(""); try { await onSave(definition()); setBaseline(keyOf(nodes, edges)); setUndoStack([]); setRedoStack([]); setMessage("Черновик сохранён"); } catch (error) { setMessage(error instanceof Error ? error.message : "Не удалось сохранить маршрут"); } finally { setBusy(false); } };
  const publish = async () => { setBusy(true); setMessage(""); try { if (changed) await onSave(definition()); const next = await onPublish(definition()); if (next) { const nextNodes = toNodes(next); const nextEdges = toEdges(next); setNodes(nextNodes); setEdges(nextEdges); setSelectedId(nextNodes[0]?.id ?? ""); setBaseline(keyOf(nextNodes, nextEdges)); setUndoStack([]); setRedoStack([]); setMessage(`Версия ${workflow.version} опубликована`); } } catch (error) { setMessage(error instanceof Error ? error.message : "Не удалось опубликовать маршрут"); } finally { setBusy(false); } };
  const cancel = () => { const nextNodes = toNodes(workflow); const nextEdges = toEdges(workflow); setNodes(nextNodes); setEdges(nextEdges); setSelectedId(nextNodes[0]?.id ?? ""); setUndoStack([]); setRedoStack([]); setMessage(""); };
  const remove = () => { if (!selected || selected.data.kind === "start") return; checkpoint(); setNodes((current) => current.filter((node) => node.id !== selected.id)); setEdges((current) => current.filter((edge) => edge.source !== selected.id && edge.target !== selected.id)); setSelectedId(""); };
  return <section className={`process-workflow-graph approvals-view tone-${accent}`} aria-label={`Конструктор маршрута: ${processName}`}>
    <header className="process-workflow-graph-toolbar"><div><span>Независимый маршрут</span><h2>{processName}</h2><p>Полноценная схема этого раздела хранится и публикуется отдельно.</p></div><div className="process-workflow-actions">{message ? <span role="status">{message}</span> : null}<div className="workflow-history-actions" role="group" aria-label="История изменений маршрута"><Button appearance="subtle" icon={<ArrowUndo24Regular />} aria-label="Назад (Ctrl+Z)" disabled={busy || !undoStack.length} onClick={undo} /><Button appearance="subtle" icon={<ArrowRedo24Regular />} aria-label="Вперёд (Ctrl+Shift+Z)" disabled={busy || !redoStack.length} onClick={redo} /></div><Button appearance="subtle" disabled={busy || !changed} onClick={cancel}>Отменить</Button><Button appearance="primary" icon={<Save24Regular />} disabled={busy || !changed} onClick={() => void save()}>Сохранить</Button><Button appearance="secondary" disabled={busy || workflow.status !== "draft"} onClick={() => void publish()}>Опубликовать v{workflow.version}</Button></div></header>
    <div className="workflow-layout"><aside className="workflow-library"><div className="workflow-template-summary"><span className="detail-kicker">Шаблон</span><h2>{workflow.name}</h2><p>Черновик v{workflow.version} · опубликована v{workflow.publishedVersion ?? "—"}</p><dl><div><dt>Блоки</dt><dd>{nodes.length}</dd></div><div><dt>Связи</dt><dd>{edges.length}</dd></div></dl></div><div className="node-library"><strong>Новый объект маршрута</strong><Button appearance="subtle" icon={<CheckmarkCircle24Regular />} onClick={() => add("approval")}>Согласование</Button><Button appearance="subtle" icon={<BranchFork24Regular />} onClick={() => add("condition")}>Условие</Button><Button appearance="subtle" icon={<Add24Regular />} onClick={() => add("parallel")}>Параллельные ветки</Button><Button appearance="subtle" icon={<ArrowDownload24Regular />} onClick={() => add("correction")}>Доработка</Button></div><div className="workflow-help"><strong>Как работать со схемой</strong><span>Перетаскивайте блоки и соединяйте точки на границах. Каждый раздел сохраняет собственную схему.</span></div></aside>
      <div className="workflow-canvas" aria-label={`Карта процесса: ${processName}`}><div className="workflow-canvas-heading"><div><span>Карта процесса</span><strong>{processName}</strong></div><div className="workflow-canvas-legend"><span>Согласование</span><span>Правило</span><span>Доработка</span></div></div><ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} onNodesChange={onNodesChange} onEdgesChange={onEdgesChange} onConnect={connect} onNodeDragStart={() => { dragStart.current = snapshot(); }} onNodeDragStop={(_event, node) => { const before = dragStart.current; dragStart.current = undefined; const prior = before?.nodes.find((item) => item.id === node.id); if (before && prior && (prior.position.x !== node.position.x || prior.position.y !== node.position.y)) { setUndoStack((current) => [...current, before]); setRedoStack([]); } }} onNodeClick={(_event, node) => setSelectedId(node.id)} onPaneClick={() => setSelectedId("")} fitView fitViewOptions={{ padding: .2 }} minZoom={.45} maxZoom={1.6} proOptions={{ hideAttribution: true }}><Background variant={BackgroundVariant.Dots} gap={18} size={1} color="#c7d2df" /><MiniMap pannable zoomable nodeColor="#d9e8f6" maskColor="rgba(245,247,250,.74)" /><Controls showInteractive={false} /></ReactFlow></div>
      <aside className={`workflow-inspector${selected ? "" : " is-empty"}`} aria-label="Настройки выбранного блока">{selected ? <><div className="inspector-heading"><CircleEdit24Regular /><div><strong>Настройка блока</strong><span>{labels[selected.data.kind]}</span></div><Button appearance="subtle" icon={<Dismiss24Regular />} aria-label="Закрыть настройки блока" onClick={() => setSelectedId("")} /></div><label>Название<Input value={selected.data.label} onChange={(_, data) => update({ label: data.value })} /></label><label>Правило или исполнитель<Textarea resize="vertical" value={selected.data.detail} onChange={(_, data) => update({ detail: data.value })} /></label><label>Тип блока<WorkspaceSelect aria-label="Тип блока маршрута" value={selected.data.kind} onChange={(event) => update({ kind: event.target.value as ApprovalNodeKind })}>{Object.entries(labels).map(([kind, label]) => <option key={kind} value={kind}>{label}</option>)}</WorkspaceSelect></label>{selected.data.kind === "approval" ? <><label>Должность согласующего<WorkspaceSelect aria-label="Должность согласующего" value={String(selected.data.approverPositionId ?? "")} onChange={(event) => update({ approverPositionId: event.target.value || undefined, approverUserId: undefined })}><option value="">Определяется ролью</option>{positions.map((position) => <option key={position.id} value={position.id}>{position.name}</option>)}</WorkspaceSelect></label><label>Конкретный сотрудник<WorkspaceSelect aria-label="Конкретный согласующий" value={String(selected.data.approverUserId ?? "")} onChange={(event) => update({ approverUserId: event.target.value || undefined, approverPositionId: undefined })}><option value="">Определяется ролью</option>{people.map((person) => <option key={person.id} value={person.id}>{person.name} · {person.jobTitle ?? person.role}</option>)}</WorkspaceSelect></label></> : null}{selected.data.kind === "parallel" ? <label>Завершение параллельных веток<WorkspaceSelect aria-label="Завершение параллельных веток" value={String(selected.data.decisionMode ?? "all")} onChange={(event) => update({ decisionMode: event.target.value })}><option value="all">Нужны решения всех</option><option value="any">Достаточно одного решения</option></WorkspaceSelect></label> : null}<Tooltip content="Стартовый блок удалить нельзя" relationship="description"><Button appearance="subtle" icon={<Delete24Regular />} disabled={selected.data.kind === "start"} onClick={remove}>Удалить блок</Button></Tooltip></> : null}</aside>
    </div>
  </section>;
}
